### ISSUE TITLE
不支持评论组件嘛

### ISSUE THREAD

**Issue by myannnascar** [AirboZH/halo-plugin-chirpy#10]
好似不显示评论

**Comment by AirboZH** [comment]
你说的是主题中的评论组件么？

如果是的话我会把这个is移动到主题仓库下，
主题的评论支持在最近版本中就有啦，v1.0.6和v1.0.7中有支持，
其中v1.0.7修复了一个bug，应该是没什么问题啦。

如果不是的话请补充描述一下~
谢谢

**Comment by AirboZH** [comment]
像这样？
![image](https://github.com/AirboZH/halo-plugin-chirpy/assets/50261327/4ce9e7cc-374a-4a11-8651-2bd6f8698e8d)
![image](https://github.com/AirboZH/halo-plugin-chirpy/assets/50261327/7106a9c5-9c16-46d7-93d2-3f0aff3ea136)

**Comment by AirboZH** [comment]
> 更新主题版本之后可以了，谢谢啦

好的，有其他问题都可以随时交流~~
