### ISSUE TITLE
官方编辑器二次编辑丢失tip属性效果

### ISSUE THREAD

**Issue by fengin** [AirboZH/halo-plugin-chirpy#14]
主题效果的tips info warning...等效果，第一次保存生效，后面再打开编辑器编辑发布一次就失效了，好像再打开编辑器info\warning等编辑数据丢失，请修复下对对应插件的bug

**Comment by AirboZH** [comment]
好的，收到问题

**Comment by PosiedChoss** [comment]
我也遇到了这个问题, 等待亲爱的大佬更新噢

**Comment by hxabcd** [comment]
这个项目还在更新吗，我也遇到了这个问题，希望可以尽早修复

**Comment by AirboZH** [comment]
实在抱歉，最近工作原因时间不是很多。
我最近抽时间解决一下！感谢大家支持

**Comment by AirboZH** [comment]
久等了
![img_v3_02ef_322e6b10-efaf-4de0-a050-35217562dbag](https://github.com/user-attachments/assets/542d363d-dad5-4338-abca-b832e0a65b3b)
